name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
      
      - name: Install pylint and Run pylint
        run: | 
          pip install pylint
          pylint $(git ls-files '*.py')

      # Announces CI is over
      - name: Completion
        run: echo "CI has been completed for $GITHUB_WORKSPACE!"
